### ISSUE TITLE
Editor area 

### ISSUE THREAD

**Issue by pschulz** [sevdokimov/RegexUtil#2]
If the IDEA Plugin runs with IDEA's darcula theme, the white editor areas could make people blind ;-)
It would be great to support the same styles here, as they are set in IDEA (the rest of the plugin behaves perfectly).
But I believe that just changing https://github.com/sevdokimov/RegexUtil/blob/master/SwingControls/src/com/ess/regexutil/swingadapter/SwingAdapter.java#L133 is not enough, because you added your own kind of styling.

BTW Thank you for this great tool.

![Regex Tester IDEA with Darcula Theme](https://cloud.githubusercontent.com/assets/724393/5411951/c66b1d64-8207-11e4-8b2a-d64d003379bf.png)

**Comment by sevdokimov** [comment]
Fixed in 2.0.0
