### ISSUE TITLE
Support named group expressions

### ISSUE THREAD

**Issue by epearson-nmdp** [sevdokimov/RegexUtil#4]
Thanks for a great tool! Currently, the IDEA plugin (at least) doesn't seem to support named capturing groups in Java regular expressions, e.g.

```
(?<firstName>\p{Alpha}+)\s+(?<lastName>\p{Alpha}+)
```

At least, it would be great if it was able to parse these.  Better, if it could show group names in tooltips.

**Comment by sevdokimov** [comment]
Fixed in 2.0.0
