### ISSUE TITLE
line breaks vanished when pasting some text with line breaks

### ISSUE THREAD

**Issue by BlurryFlurry** [sevdokimov/RegexUtil#7]
### Problem in short:
When copying and pasting contents from the editor to the regex tester, it removes every line breaks and whole contents appears in single line in regex tester.

### Environment:
Manjaro linux + i3wm
Have RegexpTester 1.0.6 Sep 15, 2018 plugin installed on:
PyCharm Professional 2019.3.1 Build #PY 566261

### Steps to reproduce:
1. Simply go the editor and select couple of text lines and copy (Ctrl+c)
2. Press Ctrl+Shift+A and type Regex Tester and hit enter, so it opens the regex tester.
3. Paste the content into the regex tester. (Ctrl+V)

### Actual results:
Pasted contents appear in the regex tester as a single text line

### Expected results:
Pasted contents appear in the regex tester as same as original texts with multiple lines.

### Proof: 
![https://imgur.com/zbOOdsJ.png](https://imgur.com/zbOOdsJ.png)

**Comment by jimklo** [comment]
same issue

**Comment by sevdokimov** [comment]
Fixed in 2.0.0
